data:
  dataset: MNIST
  data_dir: data
  num_classes: 10

model:
  hidden_size: 256
  num_layers: 2

training:
  learning_rate: 0.1
  batch_size: 64
  num_epochs: 10
  validation_split: 0.5

validation:
  batch_size: 1024